-- -----------------------------------------------------
-- Tabla `USUARIOS`
-- -----------------------------------------------------

CREATE TABLE IF NOT EXISTS `USUARIOS`
(
  `ID_USUARIO` INT(15) NOT NULL PRIMARY KEY,
  `NOMBRE` VARCHAR(60) NOT NULL,
  `APELLIDO` VARCHAR(60) NOT NULL,

  `USUARIO` VARCHAR(40) NOT NULL,
  `PASSWORD` VARCHAR(60) NOT NULL,
  `CORREO` VARCHAR(45) NOT NULL,
  `TELEFONO` VARCHAR(45) NOT NULL
);

-- -----------------------------------------------------
-- Tabla `TECNICOS`
-- -----------------------------------------------------

CREATE TABLE IF NOT EXISTS `TECNICOS` 
(
  `ID_TECNICO` INT(15) NOT NULL PRIMARY KEY,
  `NOMBRE` VARCHAR(60) NOT NULL,
  `APELLIDO` VARCHAR(60) NOT NULL,
  `USUARIO` VARCHAR(40) NOT NULL,
  `PASSWORD` VARCHAR(60) NOT NULL,
  `CALIFICACION` VARCHAR(15) NOT NULL,
  `CORREO` VARCHAR(45) NOT NULL,
  `TELEFONO` VARCHAR(45) NOT NULL
);

-- -----------------------------------------------------
-- Tabla `PRODUCTOS`
-- -----------------------------------------------------

CREATE TABLE IF NOT EXISTS `PRODUCTOS` 
(
  `ID_PRODUCTOS` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `NOMBRE` VARCHAR(45) NOT NULL
);

-- -----------------------------------------------------
-- Tabla `FACTURA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `FACTURA` 
(
  `ID_FACTURA` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `FECHA` VARCHAR(45) NOT NULL,
  `COSTO` VARCHAR(45) NOT NULL
);

-- -----------------------------------------------------
-- Tabla `AGENDA`
-- -----------------------------------------------------

CREATE TABLE IF NOT EXISTS `AGENDA` 
(
  `ID_CITA` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `FECHA` VARCHAR(45) NOT NULL,
  `HORA` VARCHAR(45) NOT NULL,
  `UBICACION` VARCHAR(45) NOT NULL,
  `USUARIOS_ID_USUARIO` INT(15) NOT NULL,
  `TECNICOS_ID_TECNICO` INT(15) NOT NULL,
  INDEX `fk_AGENDA_USUARIOS_idx` (`USUARIOS_ID_USUARIO` ASC) VISIBLE,
  INDEX `fk_AGENDA_TECNICOS1_idx` (`TECNICOS_ID_TECNICO` ASC) VISIBLE,
  CONSTRAINT `fk_AGENDA_USUARIOS`
    FOREIGN KEY (`USUARIOS_ID_USUARIO`)
    REFERENCES `USUARIOS` (`ID_USUARIO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_AGENDA_TECNICOS1`
    FOREIGN KEY (`TECNICOS_ID_TECNICO`)
    REFERENCES `TECNICOS` (`ID_TECNICO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
);